In [ ]:
import os
import pymysql
from pymysql.cursors import DictCursor
from dotenv import load_dotenv

load_dotenv()

DB_CONFIG = {
    'host': os.getenv('DB_HOST'),
    'port': int(os.getenv('DB_PORT')),
    'user': os.getenv('DB_USER'),
    'password': os.getenv('DB_PASSWORD'),
    'database': os.getenv('DB_NAME'),
    'charset': 'utf8mb4',
    'cursorclass': DictCursor
}

def connect():
    conn = pymysql.connect(**DB_CONFIG)
    return conn

conn = connect()
conn.close()

In [ ]:
import pandas as pd
BATCH_SIZE = 50

# DB 커넥션 관리
# cleansing 로직이 데이터를 가져오고 나서 5초정도 conn 유휴 시간을 고려
# 데이터 수가 적거나, 금방 처리된다면 1번 방식, 아니면 2번방식 (안정성 높음)

# 1. 연결 잡아놓고, 정제 로직 전체 처리
# 장점 - 로직구성이 간단해진다. (데이터 수 적거나, 금방 처리할 수 있을 때 활용)
# 단점 - 데이터 수가 많아지면(정제 로직이 길어지는 것), 연결이 불안정해질 수 있다.
conn = connect()
try:
    cur = conn.cursor()
    cur.execute('SELECT COUNT(*) AS cnt FROM raw_item')
    total_count = cur.fetchone()['cnt']
    print('총 raw item 수:', total_count)
    cur.close()

    for i in range(0, total_count, BATCH_SIZE): # 0, 50, 100, 150
        cur = conn.cursor()
        cur.execute(
            'SELECT * FROM raw_item WHERE raw_id > %s LIMIT %s', 
            (i, BATCH_SIZE)
        )
        datas = cur.fetchall()
        cur.close()

        df = pd.DataFrame(datas)

        # 정제로직
        # payload 부분만 꺼내서, pd.json_normalize()

        # clean 테이블에 저장하는 로직

        print('현재까지 처리한 아이템 수:', (i+1) * BATCH_SIZE)

except Exception as e:
    print('알 수 없는 오류 발생', e)
finally:
    conn.close()

100

In [ ]:
import pandas as pd
BATCH_SIZE = 50

# 2. 데이터 가져오는 부분에서 conn 연결
# 1번 방식의 반대
# 복잡도는 함수로 관리한다.

def count_raw(conn):
    cur = conn.cursor()
    cur.execute('SELECT COUNT(*) AS cnt FROM raw_item')
    total_count = cur.fetchone()['cnt']
    cur.close()
    return total_count

def get_raw_items(conn, i, size):
    cur = conn.cursor()
    cur.execute(
        'SELECT * FROM raw_item WHERE raw_id > %s LIMIT %s', 
        (i, size)
    )
    datas = cur.fetchall()
    cur.close()
    return datas

# 전체 개수 확인
conn = connect()
total_count = count_raw(conn)
conn.close()
print('총 raw item 수:', total_count)

# 배치단위로 정제
for i in range(0, total_count, BATCH_SIZE):
    try:
        conn = connect()
        datas = get_raw_items(conn, i, BATCH_SIZE)
        df = pd.DataFrame(datas)

        # 정제로직
        # payload 부분만 꺼내서, pd.json_normalize()

        # clean 테이블에 저장하는 로직

        print('현재까지 처리한 아이템 수:', (i+1) * BATCH_SIZE)

    except Exception as e:
        print('알 수 없는 오류 발생', e, i)
    finally:
        conn.close()

In [ ]:
# json dumps를 써서 문자열로 바꿔서 저장을 해놨었기 때문에,
# 가져올때는 json.loads()써서 파이썬 객체로 바꿔주는게 필요하다.
import json

json.loads(df['payload'][0])

In [ ]:
temp = df['payload'].map(lambda x: json.loads(x)).to_list()

w_df = pd.json_normalize(temp)

In [29]:
(w_df == '').sum()[(w_df == '').sum() != 0]

mi10MaxRn         95
mi10MaxRnHrmt     98
hr1MaxRn          95
hr1MaxRnHrmt      98
sumRnDur          62
sumRn             62
ddMefs            86
ddMefsHrmt        86
ddMes             78
ddMesHrmt         78
sumDpthFhsc       86
n99Rn             58
iscs              31
sumFogDur        100
dtype: int64

In [25]:
w_df.isnull().sum()[w_df.isnull().sum() != 0]

Series([], dtype: int64)

In [23]:
w_df.isna().mean().round(3)

stnId        0.0
stnNm        0.0
tm           0.0
avgTa        0.0
minTa        0.0
            ...
sumLrgEv     0.0
sumSmlEv     0.0
n99Rn        0.0
iscs         0.0
sumFogDur    0.0
Length: 62, dtype: float64

In [35]:
w_df.loc[2, 'tm'] = '2025-15-35'

In [40]:
w_df['tm_parsed'] = pd.to_datetime(w_df['tm'], format='%Y-%m-%d', errors='coerce')

In [42]:
w_df['tm_parsed'].isna().sum()

np.int64(1)

In [ ]:
w_df.drop_duplicates(['stnId', 'tm'])

In [45]:
import re

samples = ['54,000원', '$-30,042.555']

# 1. 숫자, -, .가 아닌거 제거
[float(re.sub(r'[^\d\-\.]+', '', sample)) for sample in samples]

[54000.0, -30042.555]

In [ ]:
%pip install sqlalchemy

In [ ]:
from sqlalchemy import create_engine

host = os.getenv('DB_HOST')
port = 3306
password = os.getenv('DB_PASSWORD')

engine = create_engine(f'mysql+pymysql://root:{password}@{host}:{port}/weather_db')
# protocol://username:password@host:port/db_name

# https://
df = pd.read_sql('SELECT * FROM raw_item', engine)

In [ ]:
df

In [54]:
w_df['raw_id'] = df['raw_id']

In [ ]:
df

In [55]:
w_df

,stnId,stnNm,tm,avgTa,minTa,minTaHrmt,maxTa,maxTaHrmt,mi10MaxRn,mi10MaxRnHrmt,...,avgM15Te,avgM30Te,avgM50Te,sumLrgEv,sumSmlEv,n99Rn,iscs,sumFogDur,tm_parsed,raw_id
0,108,서울,2025-01-01,2.6,-2.5,0441,8.9,1540,,,...,10.0,16.7,18.1,1.3,1.9,,,,2025-01-01,1
1,108,서울,2025-01-02,0.5,-2.9,0804,6.0,1507,,,...,9.9,16.6,18.0,1.9,2.6,,,,2025-01-02,2
2,108,서울,2025-15-35,-1.1,-5.1,0522,3.2,1551,,,...,9.8,16.5,18.0,1.3,1.9,0.0,{눈}2052-{눈}{강도0}2100-2122.,,NaT,3
3,108,서울,2025-01-04,-0.1,-5.4,0752,5.7,1503,,,...,9.7,16.4,18.0,1.6,2.3,4.4,,,2025-01-04,4
4,108,서울,2025-01-05,1.2,-0.7,0109,2.5,2353,,,...,9.6,16.3,17.9,0.3,0.4,5.3,{눈}0255-{눈}{강도0}0300-0335. {눈}0525-{눈}{강도0}060...,,2025-01-05,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,108,서울,2025-04-06,10.3,6.9,0642,15.7,1508,0.0,,...,9.7,11.6,14.6,3.7,5.3,,-{안개비}-0020. -{박무}-{박무}{강도0}0300-0525.,,2025-04-06,96
96,108,서울,2025-04-07,13.5,5.5,0649,20.1,1428,,,...,9.8,11.7,14.6,4.7,6.8,,{박무}0450-{박무}{강도0}0600-0855.,,2025-04-07,97
97,108,서울,2025-04-08,13.8,10.7,0622,18.9,1533,,,...,9.9,11.7,14.6,4.6,6.6,,{박무}0330-{박무}{강도0}0600-{박무}{강도0}0900-1015. {연무...,,2025-04-08,98
98,108,서울,2025-04-09,12.7,8.4,0628,18.0,1313,0.5,1926,...,10.0,11.7,14.5,2.7,3.9,0.8,{비}1555-1615. {비}1804-2005. {비}2350-{비}{강도0}2400-,,2025-04-09,99
99,108,서울,2025-04-10,13.2,8.8,0657,19.1,1515,0.0,,...,10.1,11.7,14.5,3.8,5.5,0.0,{연무}0235- -{비}-{비}{강도0}0300-0325. {연무}0520-{연무...,,2025-04-10,100

In [ ]:
from database import connect as db_connect
# import 후에, 해당 모듈을 수정하면 restart kernel해서 최신화 해줘야함.

db_connect()

연결

In [ ]:
# clean = pd.DataFrame({
#     "obs_dt" : pd.to_datetime(w_df["tm"], errors="coerce"),
#     "stn_id" : w_df["stnId"].astype(str).str.zfill(3),
#     "stn_nm" : w_df["stnNm"].str.strip(),
#     "avg_ta" : pd.to_numeric(w_df["avgTa"], errors="coerce"),
#     "sum_rn" : pd.to_numeric(w_df["sumRn"], errors="coerce"),
#     "raw_id" : w_df["raw_id"],
# })

# clean.to_sql("clean_weather", engine,
#     if_exists="replace", index=False,
#     chunksize=1000)

100

In [ ]:
import pandas as pd
BATCH_SIZE = 50

def count_raw(conn):
    cur = conn.cursor()
    cur.execute('SELECT COUNT(*) AS cnt FROM raw_item')
    total_count = cur.fetchone()['cnt']
    cur.close()
    return total_count

def get_raw_items(conn, i, size):
    cur = conn.cursor()
    cur.execute(
        'SELECT * FROM raw_item WHERE raw_id > %s LIMIT %s', 
        (i, size)
    )
    datas = cur.fetchall()
    cur.close()
    return datas

# 전체 개수 확인
conn = connect()
total_count = count_raw(conn)
conn.close()
print('총 raw item 수:', total_count)

# 배치단위로 정제
for i in range(0, total_count, BATCH_SIZE):
    try:
        conn = connect()
        datas = get_raw_items(conn, i, BATCH_SIZE)
        df = pd.DataFrame(datas)

        # 정제로직
        temp = df['payload'].map(lambda x: json.loads(x)).to_list()
        w_df = pd.json_normalize(temp)

        # clean 테이블에 저장하는 로직
        # station INSERT
        stations = w_df.drop_duplicates(['stnId'])[['stnId','stnNm']].values.tolist()
        # [ ['108', '서울'], ['109', '부산'] ]

        cur = conn.cursor()
        cur.executemany(
            'INSERT IGNORE INTO tb_station(id, name) VALUES (%s, %s)', 
        stations)
        conn.commit()
        cur.close()

        # temparature INSERT
        temperatures = w_df[['stnId', 'avgTa', 'minTa', 'maxTa', 
                                'minTaHrmt', 'maxTaHrmt', 'tm']].values.tolist()

        cur = conn.cursor()
        cur.executemany(
            f"""INSERT IGNORE INTO tb_temperature(station_id, average, minimum, maximum, 
                                                minimum_time, maximum_time, observed_dt)
                                        VALUES ({','.join(['%s']*7)})""",
            temperatures
        )
        conn.commit()
        cur.close()
        # rainy INSERT


        print('현재까지 처리한 아이템 수:', (i//BATCH_SIZE+1)*BATCH_SIZE)

    except Exception as e:
        print('알 수 없는 오류 발생', e, i)
    finally:
        conn.close()

총 raw item 수: 100
현재까지 처리한 아이템 수: 50
현재까지 처리한 아이템 수: 100

In [101]:
clean = pd.DataFrame({
    "obs_dt" : pd.to_datetime(w_df["tm"], errors="coerce"),
    "stn_id" : w_df["stnId"].astype(str).str.zfill(3),
    "stn_nm" : w_df["stnNm"].str.strip(),
    "avg_ta" : pd.to_numeric(w_df["avgTa"], errors="coerce"),
    "sum_rn" : pd.to_numeric(w_df["sumRn"], errors="coerce"),
    # "raw_id" : w_df["raw_id"],
})

In [ ]:
clean

In [ ]:
monthly = (clean
    .assign(ym=clean["obs_dt"].dt.to_period("M").astype(str))
    .groupby(["stn_id", "stn_nm", "ym"], as_index=False)
    .agg(avg_ta=("avg_ta", "mean"),
        max_ta=("avg_ta", "max"),
        sum_rn=("sum_rn", "sum"),
        days=("obs_dt", "count")
    ))

In [ ]:
clean

In [ ]:
monthly.to_sql(
    "mart_weather_monthly", engine,
    if_exists="replace", index=False
)

3

In [ ]:
# groupby -> 하나로 합치는 것인데 (108, 109, 110 - 50개씩 -> 108, 109, 110 3개)
# transform -> 하나로 합친 것을 다시 행단위로 풀어주는 역할 (3개 -> 150개)
clean['ma7'] = clean.groupby('stn_id')['avg_ta'].transform(lambda s: s.rolling(7).mean()).round(1)

In [122]:
clean

       obs_dt stn_id stn_nm  avg_ta  sum_rn   ma7
0  2025-02-20    108     서울    -2.9     NaN   NaN
1  2025-02-21    108     서울    -2.5     NaN   NaN
2  2025-02-22    108     서울    -2.3     NaN   NaN
3  2025-02-23    108     서울    -3.6     NaN   NaN
4  2025-02-24    108     서울    -1.3     NaN   NaN
5  2025-02-25    108     서울     2.1     NaN   NaN
6  2025-02-26    108     서울     3.7     NaN  -1.0
7  2025-02-27    108     서울     5.8     NaN   0.3
8  2025-02-28    108     서울     7.8     NaN   1.7
9  2025-03-01    108     서울     8.5     0.6   3.3
10 2025-03-02    108     서울     8.3    11.8   5.0
11 2025-03-03    108     서울     3.1    10.4   5.6
12 2025-03-04    108     서울     2.5     4.0   5.7
13 2025-03-05    108     서울     4.8     0.0   5.8
14 2025-03-06    108     서울     4.8     NaN   5.7
15 2025-03-07    108     서울     5.3     NaN   5.3
16 2025-03-08    108     서울     5.8     NaN   4.9
17 2025-03-09    108     서울     6.9     NaN   4.7
18 2025-03-10    108     서울     8.0     NaN   5.4
19 2025-03-11    108     서울     9.4     NaN   6.4
20 2025-03-12    108     서울     8.5     0.0   7.0
21 2025-03-13    108     서울     8.9     NaN   7.5
22 2025-03-14    108     서울    12.4     NaN   8.6
23 2025-03-15    108     서울    12.6     0.0   9.5
24 2025-03-16    108     서울     4.9     0.8   9.2
25 2025-03-17    108     서울     2.5     0.4   8.5
26 2025-03-18    108     서울     2.1     9.9   7.4
27 2025-03-19    108     서울     2.4     NaN   6.5
28 2025-03-20    108     서울     8.2     NaN   6.4
29 2025-03-21    108     서울    11.6     NaN   6.3
30 2025-03-22    108     서울    12.8     NaN   6.4
31 2025-03-23    108     서울    15.2     NaN   7.8
32 2025-03-24    108     서울    15.5     0.0   9.7
33 2025-03-25    108     서울    12.7     NaN  11.2
34 2025-03-26    108     서울    15.5     NaN  13.1
35 2025-03-27    108     서울    13.7     0.3  13.9
36 2025-03-28    108     서울     6.5     NaN  13.1
37 2025-03-29    108     서울     3.3     0.0  11.8
38 2025-03-30    108     서울     3.3     0.0  10.1
39 2025-03-31    108     서울     7.7     NaN   9.0
40 2025-04-01    108     서울    10.1     NaN   8.6
41 2025-04-02    108     서울     8.9     0.0   7.6
42 2025-04-03    108     서울     9.8     NaN   7.1
43 2025-04-04    108     서울    10.6     NaN   7.7
44 2025-04-05    108     서울     8.0    22.8   8.3
45 2025-04-06    108     서울    10.3     0.0   9.3
46 2025-04-07    108     서울    13.5     NaN  10.2
47 2025-04-08    108     서울    13.8     NaN  10.7
48 2025-04-09    108     서울    12.7     0.8  11.2
49 2025-04-10    108     서울    13.2     0.0  11.7